version: '2'
services:
  nginx:
    image: shippingdocker/nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  php:
    image: shippingdocker/php:latest
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  memcached:
    image: memcached:latest
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"